spring:
  application:
    name: springbootlayeredapp

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: R@m@devi395
    driver-class-name: oracle.jdbc.OracleDriver
